#!/usr/bin/env zsh

FONT_FACE="JetBrainsMono Nerd Font"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins-desktop"
PLUGIN_SHARED_DIR="$HOME/.config/sketchybar/plugins"

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"

sketchybar --bar \
    height=40 \
    color=0x00000000 \
    margin=0 \
    sticky=on \
    padding_left=2 \
    padding_right=0 \
    notch_width=222 \
    display=all

sketchybar --default \
    background.color=0x66494d64 \
    icon.color=0xff24273a \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=26 \
    icon.font="$FONT_FACE:Medium:15.0" \
    icon.padding_left=5 \
    icon.padding_right=5 \
    label.color=0xff24273a \
    label.font="$FONT_FACE:Bold:14.0" \
    label.y_offset=1 \
    label.padding_left=0 \
    label.padding_right=5

sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        label.color=0x668AADF5 \
        background.drawing=on \
        label.padding_left=-2 \
        label.padding_right=9 \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$PLUGIN_SHARED_DIR/aerospace.sh $sid"
done

#sketchybar --add item current_space left \
#    --set current_space \
#    background.color=0xfff5a97f \
#    label.drawing=off \
#    script="$PLUGIN_SHARED_DIR/current_space.sh" \
#    --subscribe current_space space_change mouse.clicked
#
#sketchybar --add item front_app left \
#    --set front_app \
#    background.color=0xffa6da95 \
#    background.padding_left=0 \
#    background.padding_right=0 \
#    icon.y_offset=1 \
#    label.drawing=no \
#    script="$PLUGIN_SHARED_DIR/front_app.sh" \
#    --add item front_app.separator left \
#    --set front_app.separator \
#    background.color=0x00000000 \
#    icon= \
#    icon.color=0xffa6da95 \
#    icon.font="$FONT_FACE:Bold:23.0" \
#    icon.padding_left=0 \
#    icon.padding_right=0 \
#    icon.y_offset=1 \
#    label.drawing=no \
#    --add item front_app.name left \
#    --set front_app.name \
#    background.color=0x00000000 \
#    icon.drawing=off \
#    label.font="$FONT_FACE:Bold:16.0" \
#    label.color=0xffcad3f5 \
#    label.padding_left=5
#
#sketchybar --add bracket front_app_bracket \
#    front_app \
#    front_app.separator \
#    front_app.name \
#    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    background.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_SHARED_DIR/clock.sh"

sketchybar -m --add item dark_mode right \
    --set dark_mode \
        icon= \
        icon.color=0xffa6da95 \
        icon.y_offset=1 \
        icon.padding_left=7 \
        icon.padding_right=1 \
        click_script="$PLUGIN_SHARED_DIR/dark-mode-switcher.sh true" \
        script="$PLUGIN_SHARED_DIR/dark-mode-switcher.sh"

sketchybar -m --add item tunnelblick right \
    --set tunnelblick \
        icon=󱠽 \
        icon.color=0xff959595 \
        icon.y_offset=1 \
        icon.padding_left=7 \
        icon.padding_right=1 \
        click_script="$PLUGIN_SHARED_DIR/tunnelblick.sh gkrebs false" \
        script="$PLUGIN_SHARED_DIR/tunnelblick.sh gkrebs true"

sketchybar -m --add item flow right \
    --set flow \
        label.drawing=true \
        label.padding_left=-5 \
        label.padding_right=6 \
        click_script="$PLUGIN_SHARED_DIR/flow-click.sh" \
        script="$PLUGIN_SHARED_DIR/flow.sh"

sketchybar --add event spotify_change $SPOTIFY_EVENT \
    --add item spotify right \
    --set spotify \
    icon= \
    icon.y_offset=1 \
    label.drawing=off \
    label.padding_left=3 \
    script="$PLUGIN_DIR/spotify.sh" \
    --subscribe spotify spotify_change mouse.clicked

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
